name: Fabric CI

on:
  push:
    branches: [ master ]
    paths: 
      - '**.json'
      - '**.properties'
      - '**.gradle'
      - '**.java'
      - '**.yml'
  pull_request:
    branches: [ master ]

jobs:
  buildAndRunForSomeVersions:
      name: Run tests for ${{ matrix.minecraftVersion }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          minecraftVersion:
            - latest
      steps:
        - name: Minecraft Tests
          uses: Geometrically/fabric-test-runner@v1
        - uses: actions/checkout@v2
          with:
            lfs: true
        - uses: Geometrically/fabric-test-runner@v1
          id: testRunner
          with:
            minecraftVersion: ${{ matrix.minecraftVersion }}
            runServerTest: false
        - uses: actions/upload-artifact@v1
          with:
            name: Builds
            path: build/libs
        - name: Publish to github packages
          env:
            KEY_STORE_PASS: ${{ secrets.KEY_STORE_PASS }}
            KEY_STORE_ALIAS: ${{ secrets.KEY_STORE_ALIAS }}
            KEY_STORE_KEY_PASS: ${{ secrets.KEY_STORE_KEY_PASS }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: ./gradlew publish --no-daemon
